name: Error Report
description: File a an error report for Dynamics 365 guidance content
title: "[ERROR]: "
labels: ["bug", "triage"]
assignees:
  - rachel-profitt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this error report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: myemail@example.com
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the error you see in the documentation, or the correction you suggest
      description: Also, tell us what you expected to see?
      placeholder: Tell us what you want to see!
      value: "Something is wrong in the content!"
    validations:
      required: true
  - type: input
    id: siteURL
    attributes:
      label: Link to the article where the error is
      description: Please copy and paste the link to the article or place on Microsoft Learn where the error or correction is needed.
    validations:
      required: true  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true